// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mboxhdzalhiicpnhzzzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ib3hoZHphbGhpaWNwbmh6enptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0Mzg5NTEsImV4cCI6MjA2MDAxNDk1MX0.rs2SGLHNbL2sBy7AIv2CxAE6h8zdX7pvM4HLNdfYNco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);